### ISSUE TITLE
Tag are Objects

### ISSUE THREAD

**Issue by beard1ess** [bgshacklett/extropy#17]
'Tag' attribute comes back as an object type.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

Not sure if they have to be list.

**Comment by bgshacklett** [comment]
It looks like this was occurring in the event that there was only a single tag. PowerShell was unboxing the array automatically and returning the single tag inside as a Hashtable. This should be fixed in #18.

**Comment by bgshacklett** [comment]
Attempted fix in #18. Actually fixed in #22
