### ISSUE TITLE
Project Needs A License

### ISSUE THREAD

**Issue by garethsaxby** [bgshacklett/extropy#36]
This project needs an applicable Open Source license for others to be able to use this.
Without a license, other users aren't able to actually use your code legally; GitHub's ToS only allows for basic GitHub interactions if there is no license, and no actual usage of the code.

Good resources regarding GitHub licensing:
https://help.github.com/articles/licensing-a-repository/
https://choosealicense.com/

For Rackspace OSS, the Apache License is typically mandated, but as this is within your own user on GitHub, you're likely free to pick.

**Comment by bgshacklett** [comment]
Gareth, thanks for bringing this up! It was merely an oversight. Apache it is! If you have any other concerns, please don't hesitate to re-open this issue.
